# Generated by Django 4.2.2 on 2023-06-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribeList',
            new_name='contact',
        ),
    ]
